### ISSUE TITLE
Перед защитой

### ISSUE THREAD

**Issue by baileys-li** [htmlacademy-react/2412877-six-cities-15#23]
### [Д3](https://up.htmlacademy.ru/react/15/criteries#d3)
можно объединить в один 
https://github.com/htmlacademy-react/2412877-six-cities-15/blob/6939d1cace44b75291b94c4552e3e9744b4b1160/src/const.ts#L52-L53

### [Б9](https://up.htmlacademy.ru/react/15/criteries#b9)
Нужно в единсваенном числе и поля не UPPER_CASE. В этом файле такого много. Поищи в ещё в всём проекте по поиску `const` и `enum` (конст объекты тоже считаются енамами, если они без вложеностей)
https://github.com/htmlacademy-react/2412877-six-cities-15/blob/6939d1cace44b75291b94c4552e3e9744b4b1160/src/const.ts#L58-L63

### Не обязательно сейчас
Из-за того, что ты фетчишь эти данные только при первой загрузки приложения, когда юзер логинеться, добавляет что-то в избранное и разлогинивается, то у него стейт сбрасывается
https://github.com/htmlacademy-react/2412877-six-cities-15/blob/d2d40524b58e11ae86f653f7bd002d6c375bc617/src/index.tsx#L15-L21

Тут RatingName и читаемей `Record<string, string>`
https://github.com/htmlacademy-react/2412877-six-cities-15/blob/6939d1cace44b75291b94c4552e3e9744b4b1160/src/const.ts#L70

**Comment by baileys-li** [comment]
@Artlashmanov

**Comment by Artlashmanov** [comment]
Если успею поправлю, сейчас реально некогда ) Что нужно сейчас сделать чтобы дальше отправить ?
